[package]
name = "diavolo-client"
version = "0.0.1"
authors = ["Andrew Clarkson <andrew@clarkson.mn>"]
edition = "2018"

[dependencies]
diavolo-core = { version = "0.0.1", path = "../core" }
tokio = { version = "0.2", features = ["full"] }