[package]
name = "diavolo-core"
version = "0.0.1"
authors = ["Andrew Clarkson <andrew@clarkson.mn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


